services:
  mongodb:
    image: arm64v8/mongo:4.4.18
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot
    volumes:
      - mongodb-data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "8001:3001"
    volumes:
      - ./backend:/usr/src/app
    command: python main.py
    env_file:
      - ./.env

volumes:
  mongodb-data:
    driver: local
