name: todo-app
services:
  nginx:
    image: nginx:1.27.3
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 8000:80
    depends_on:
      - frontend
      - backend
  frontend:
    image: "node:23-alpine3.20"
    user: "root"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend/:/usr/src/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
  backend:
    image: todo-app/backend
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app
    expose:
      - "3001"
    ports:
      - "8001:3001"
    command: "python main.py"
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true
