name: farm-app
services:
  mongodb:
    image: arm64v8/mongo:4.4.18
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=rootroot
    volumes:
      - ./db:/data/db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 8000:80
    depends_on:
      - frontend
      - backend
  frontend:
    image: farm/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: "root"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend/:/usr/src/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: farm/backend
    volumes:
      - ./backend/:/usr/src/app
    expose:
      - "3001"
    ports:
      - "8001:3001"
    command: "python main.py"
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true
